cmake_minimum_required(VERSION 2.8)

set(${PROJECT_NAME}_MAJOR 0)
set(${PROJECT_NAME}_MINOR 0)
set(${PROJECT_NAME}_PATCH 2)
set(${PROJECT_NAME}_TWEAK 2)

set(${PROJECT_NAME}_VERSION "${${PROJECT_NAME}_MAJOR}.${${PROJECT_NAME}_MINOR}.${${PROJECT_NAME}_PATCH}.${${PROJECT_NAME}_TWEAK}")
